apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-tei
spec:
  selector:
    matchLabels:
      app: hf-tei
  template:
    metadata:
      labels:
        app: hf-tei
    spec:
      volumes:
       - name: data
         emptyDir: {}
       - name: dshm
         emptyDir:
              medium: Memory
      nodeSelector:
         cloud.google.com/compute-class: "Balanced"
      containers:
      - name: embeddings
        image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
        imagePullPolicy: Always
        resources:
            requests:
                cpu: "2"
                memory: "2Gi"
        env:
            - name: model-id
              value: WhereIsAI/UAE-Large-V1
            - name: shm-size
              value: 1g
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /data
              name: data
---
apiVersion: v1
kind: Service
metadata:
  name: tei-embedding
spec:
  type: LoadBalancer
  selector:
    app: hf-tei
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80